services:
  - type: web
    name: horse-racing-calculator
    env: node
    plan: free
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: horse-racing-calculator-redis
          property: connectionString

  - type: redis
    name: horse-racing-calculator-redis
    ipAllowList: []
    plan: free